### ISSUE TITLE
Suggestions concerning the Index File

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#10]
First of all thank you for this plugin! The moment I saw in Discord that you submitted this plugin, I knew I could uninstall Scrivener with good conscience :)

I think there are pitfalls with the index files that could be avoided easily. First, the index file probably does not play well with other plugins that automatically change the content of notes, for example the[ filename-heading-sync-plugin](https://github.com/dvcrn/obsidian-filename-heading-sync/). For me, the filename-header-sync automatically put in a header in the Index fle, which I believe caused some initial problems I had. To "inform" other plugins that the index file is not to be touched, maybe you could at some unique item in the yaml-header, maybe some sort of `doNotTouch: true`? (I also created [a corresponding issue at the other repo](https://github.com/dvcrn/obsidian-filename-heading-sync/issues/22).)

A second idea might be to hide the Index file to reduce the change of any accidental changes by the user. While I am not sure whether this works by prepending a dot to the filename (I think I read sth that Obsidian would then have issues reading the file), it would at least be possible to use some css to hide the Index file alltogether. I used for example this:

```css
.nav-file-title[data-path$="Index.md"] {
	display: none;
}
```
You could may always create use a long UUID for the Indexfile name and hide fiels with exactly that nime automatically via css?

**Comment by kevboh** [comment]
Hey! Glad you like it.

If a convention emerges for marking notes as sacrosanct I'll adopt it here, it's a good suggestion. I don't want to lead that effort, since longform very purposefully doesn't touch files.

I don't want to hide anything in the core explorer. I think it creates accessibility issues, and is liable to confuse people who don't expect it. I may eventually style project folders there, but nothing else.
