### ISSUE TITLE
Add a "delete" option for drafts?

### ISSUE THREAD

**Issue by Moonbase59** [kevboh/longform#16]
It’s just so much more convenient to work in the "Longform" pane than in the file explorer. Thus, my question: Could a "delete" option for **drafts** be added? (Rename we already have …)

**Comment by kevboh** [comment]
Okay, I've thought about this feature a lot in the context of #35 and I've decided to not implement it. Because drafts are now the basis of projects rather than a subfolder + a subset of the YAML, deleting a draft is now both simpler and more complicated depending on your setup: either you're deleting a folder somewhere in your vault or you're deleting a smattering of files spread across it.

Because drafts can have custom scene folders and really be located anywhere, and because they can _ignore files_ in those scene folders, a "delete draft" feature would have to make assumptions about what the user would and wouldn't want deleted. That's fine—a dialog can communicate those assumptions—but at that point it becomes easier for someone to do this in the explorer than to trust a dialog box. To that end, I'm going to skip this for now. If it becomes clear that draft deletion is sorely needed I'll revisit this.
