### ISSUE TITLE
Longform Losing Project Every Time I Exit Obsidian

### ISSUE THREAD

**Issue by jgalleg4** [kevboh/longform#163]
For some reason, Longform has started to lose my project every time I exit Obsidian. I do not lose the files themselves, but I have to recreate the entire Longform project from scratch every time I exit and relaunch Obsidian. It has been working fine for months, but it has suddenly changed for some unknown reason.

**Comment by kevboh** [comment]
Do you have an errors in the console? When you say you have to "recreate the entire project," do you mean the index file itself is being deleted or overwritten somehow?

**Comment by kevboh** [comment]
This is helpful, thank you. I can add some more protective code around metadata reads. @jgalleg4, if you could share errors from the console as well it would be extremely helpful.

**Comment by ballymacad** [comment]
I'm experiencing this issue, but only when I open obsidian on one of my mobile devices (using obsidian sync). 
Steps that created the issue for me:
1. Set up longform project on pc. Everything looks good.
2. Open obsidian on my tablet. Allow obsidian to sync. This is where the longform project disappears for me, even if I do not touch those files. I have noticed that even when I have not made any changes to or even opened the longform project files, there is one longform file that always syncs and I'm not sure why.
3. Move back to my PC. The longform project is still missing. All files and the Index are unchanged.

I'm happy to send additional information if you can let me know what other info you need.

Thanks for working on this, because this plugin is amazing!!

**Comment by kevboh** [comment]
Odd. Can you share the index file either here or email it to me (kb@kevinbarrett.org)? 99% of the time there is malformed YAML in it causing this. Not sure about the conflict with Sync, very strange.

**Comment by kevboh** [comment]
Is this still happening? In the latest release there's a small fix that should at least circumvent a full crash. Closing; comment if you're still seeing this!
