### ISSUE TITLE
Feature Request: Add compile step to exclude headings from compilation

### ISSUE THREAD

**Issue by sync0** [kevboh/longform#165]
**Describe the solution you'd like**
Since I use pandoc for export to PDF, which supports adding `{.noexport}` to headings to be excluded from processing, it would be useful to have similar support in longform. The idea would be that headings marked in this way, for example `## Exclude content under this heading {.noexport}`, should be excluded from the markdown file compiled by longform. 

As a side note, in pandoc, whenever a heading is marked in this way, all its subheadings are likewise excluded from export processing, even when they're not explicitly marked with `{.noexport}`.

PD: The feature I describe could also solve another feature request: [Compile Step Request: Delete headers #57](https://github.com/kevboh/longform/issues/57)

Thank you so much for the great plugin.

**Comment by xDovos** [comment]
yeah it would be great to either exclude headers or to just whitelist one header name and ignore all other ones.
it would allow a more complex setup for the scenes like tasks or inline metadata with navigation links or dataview queries.
that could for example be "## scene" and replace "scene" with the file name or a value in the yaml to set the final scene name.

**Comment by kevboh** [comment]
Sorry, I'm really struggling to understand the request here. Is it for a step that strips headers if they match certain patterns?

**Comment by xDovos** [comment]
We basically want to have additional things like a todo list inside the separate notes and a way to remove that from the compiled script without doing it manually.
The OGs idea was to remove headers by saying which one we don't want (blacklist)
And my idea is to make a whitelist with the header name that holds the actual text. 
And because that would be always like "chapter", it would be nice if it would be renamed to the files name

**Comment by kevboh** [comment]
This feels specific enough to be a custom user step rather than something in Longform proper. Let me know if you need help with that API.
