### ISSUE TITLE
Bug (Beta): `Show Current Project in Longform` does not do anything

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#79]
using the command does nothing; there is also no error in the console.

**Comment by kevboh** [comment]
It works for me: this might be a naming issue. Here's what it should do:

1. Open a scene for some project.
2. In the longform pane, switch to a different (multi-scene, so that it doesn't open a note) project.
3. Run the command.

It should switch back to the project corresponding to the open scene. If not, it's broken. If so, it's poorly-named :)

**Comment by chrisgrieser** [comment]
Ah, got it! Yeah, the command should be renamed, it wasn't really clear to me what it does. Maybe something like "Open Project of Current Note in Sidebar"?
