### ISSUE TITLE
Bug (Beta): Scene Navigation Commands disappear after rearranging scenes

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#80]
1. rearrange any scene in the sidebar. 
2. Then open the command palette
3. the scene navigation commands (next scene, indent scene, previous scene) are now missing

However, switching to another scene via mouse click in the sidebar fixes the issues and the respective commands re-appear in the command palette.

**Comment by kevboh** [comment]
Took a look at this, and this isn't really a bug per se. When you rearrange scenes via the mouse it shifts focus to the Longform pane. I looked into it, and I'm not sure there's a way to prevent this shift in focus. This doesn't happen on scene click because clicking a scene focuses that scene's markdown pane—the navigation commands are only available when a markdown pane with a Longform scene in it is focused.

So I think for now this is the "desired" behavior, although it's not ideal. I worry that trying to shift focus back to the previously-focused pane on scene drag could break keyboard navigation (which admittedly is pretty bad in Longform right now, and needs improvement) or some a11y constraints.

**Comment by kevboh** [comment]
See https://github.com/kevboh/longform/issues/88 for keyboard nav ticket.

**Comment by chrisgrieser** [comment]
> I worry that trying to shift focus back to the previously-focused pane on scene drag could break keyboard navigation

Tbh, the _current_ behavior does break keyboard navigation for me much more. And navigating the sidebar shouldn't be that necessary anyway, since you can already navigate the scene via the next/prev scene command. Maybe make it an option in the Longform plugin settings if you worry about breaking some people's workflows?

**Comment by kevboh** [comment]
An option makes sense, I'll take a look.

**Comment by kevboh** [comment]
Thought about it more, doesn't make sense to put it behind a setting. Fixed and made default behavior.
