### ISSUE TITLE
Bug (Beta, Critical): Changing Scenes in the Sidebar deletes Metadata of Index Note

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#86]
I hope it's okay that I am putting "Critical" in the subject, but since this bug can lead to data loss, I think it's somewhat warranted?

To reproduce:
1. have a multi-scene project where you add keys to the yaml that do not "belong" to the longform plugin.
2. do something in the sidebar that changes the longform yaml, e.g. adding/deleting/indenting scenes.
3. All yaml keys that do not belong to the longform plugin are then removed from that note.

Since it looks like some yaml gets written over all the existing yaml of the index note, I suspect that this bug could be related to #82.

Here is a brief demo of the bug

https://user-images.githubusercontent.com/73286100/182252226-74e765a2-5fb2-463d-ba29-33065a7ab29d.mov

**Comment by kevboh** [comment]
@chrisgrieser I can't seem to reproduce this locally, but I'm going to take a look at the code paths involved here. I _suspect_ this is the same issue as [the one I asked about in the discord a month or so ago](https://discord.com/channels/686053708261228577/840286264964022302/994589562082951219), where sometimes obsidian's metadata cache can be inaccurate. So what I think is happening is that your frontmatter hasn't hit the cache yet by the time you edit a scene location, so Longform dutifully asks Obsidian what the other frontmatter is, Obsidian says there is none, and Longform goes ahead and removes it.

A workaround I've used elsewhere is to not trust the cache and instead read the file, parse out the frontmatter manually, and use that instead. I can look at doing this here, but my concern is that this could introduce a performance hit. It might be fine, though, since I suspect index files will rarely be really big...

**Comment by kevboh** [comment]
One thing you can try:

1. Add your frontmatter
2. Open a different note to shift focus away from the new frontmatter (and perhaps prompt the cache to save?)
3. Wait a moment, then reorder scenes.

See if that preserves your frontmatter, out of curiosity.

**Comment by chrisgrieser** [comment]
> One thing you can try:
> 
> 1. Add your frontmatter
> 2. Open a different note to shift focus away from the new frontmatter (and perhaps prompt the cache to save?)
> 3. Wait a moment, then reorder scenes.
> 
> See if that preserves your frontmatter, out of curiosity.

yep, that seems to keep the metadata intact

**Comment by kevboh** [comment]
Okay, then it's definitely some weirdness where the cache isn't being updated fast enough. Still going to keep this open until I can look at a workaround
