### ISSUE TITLE
Longform YAML parsing and Obsidian YAML parsing seem to be inconsistent?

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#87]
not totally sure what's going on here, I think this screenshot shows the problem best. I wanted to read `this.app.metadataCache.getCache("path/to/index/note.md").frontmatter` so I can get the list of scenes for dataview, but it seems for Obsidian (and therefore also for dataview), the scenes metadata cannot be properly parsed?

![image](https://user-images.githubusercontent.com/73286100/182253697-57331e5e-b9be-459d-b2eb-e5cae002c25c.png)

I am not totally sure what the issue here is, but while documenting #86, I noticed that as soon as the yaml header only contains keys from the longform plugin, it gets parsed correctly again.

**Comment by kevboh** [comment]
This is exactly the thing I wrote about [in the Discord](https://discord.com/channels/686053708261228577/840286264964022302/994589562082951219). I have no idea why this happens, and I don't know how to prompt the cache to reindex. Something about YAML arrays seems to confuse Obsidian...

I wrote about this in the other issue you opened, but the workaround for now is to read the file yourself and parse out the frontmatter via regex, then parse that from YAML. Not ideal, but guaranteed to be correct.

I'm going to close this since there's not a lot I can do about it, but I'll reup the conversation in the Discord.

**Comment by chrisgrieser** [comment]
So I tested around with this together with @kometenstaub, and it does seem to be a problem of the longform plugin. Disabling the longform plugin and restarting Obsidian does make the yaml readable again

![image](https://user-images.githubusercontent.com/73286100/182588243-f61663bb-a7e3-4c2e-8181-c2dedb6d5cfd.png)

enabling the longform plugin breaks the yaml parsing again

---

Also, don't know if this is related, but with the longform plugin enabled, not indenting seems to also make the metadata readable

![image](https://user-images.githubusercontent.com/73286100/182588580-a02c8737-a3c8-44cd-9e16-750755456608.png)

**Comment by kometenstaub** [comment]
I don't know whether `omit` somehow mutates the original metadata cache.

https://github.com/kevboh/longform/blob/572a070db8c071be98c3487f9dbbb7cdcf0fccb5/src/model/draft-utils.ts#L144

You could try to use it without it and pick the other properties with plain TS to see whether that fixes it.

I didn't see any other instances where the metadata cache could be mutated, so I think it's worth a try.

**Comment by kevboh** [comment]
@kometenstaub it does not: https://lodash.com/docs/4.17.15#omit

To be clear, both @chrisgrieser and I are seeing this bug outside that code path, so even if `omit` did mutate its argument it wouldn't explain this, unfortunately

**Comment by chrisgrieser** [comment]
disabling the longform plugin seemed to temporarily fix the issue, O I don't know whether maybe there is something gong on here still? 🤔

**Comment by Lulullia** [comment]
Hi, I came here after bumping into this problem while trying my Templater script outside of the console… I understand it's likely there won't be a fix anytime soon, but is it possible to at least expose the YAML parsing through the API?

Something like `longform.api.parse("path/to/file")`, to avoid having to rewrite the parser when it's already used by Longform anyway?

That would be a quick "fix" that doesn't differ much from the initial way of retrieving metadata, at least for one-time scripts. I really hope it's feasible! And thanks for the plugin :)

**Comment by kevboh** [comment]
Interesting—for what it's worth, all Longform now resorts to calling `processFrontMatter` when it detects this issue to grab frontmatter and otherwise does nothing special. You could try calling that? If that doesn't work for you I can look into adding API.

**Comment by Lulullia** [comment]
Ah, I had thought it was more complex than that! (getting file contents, getting YAML, parsing YAML, turning scene list into a usable array…)

Indeed I tried it and it works like a charm! It's still not as straightforward a simply calling one method (because of the try/catch block) but since it's for a one-time script it's not really a big deal. Thanks for bringing that to my attention! I didn't think of looking through the Obsidian API for this.

If I may add though, I think it would be pretty neat to be able to get information about a Longform project by name. Not only frontmatter but also word count, and any other potential data that may be added in the future. But it's probably best to open a new issue for this?
