### ISSUE TITLE
FR: Store session data separately from config data

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#94]
right now, both are stored in `data.json`. However, it would be useful to store them separately, so that the session data could be gitignored, while the config data can be kept.

**Comment by kevboh** [comment]
Interesting. I might add a setting to let people choose between storing them in the plugin folder or in the vault—I don't fully trust the plugin folder for sync, to be honest.

**Comment by washingtonsteven** [comment]
+1 on this. The main problem I'm finding is the [`test`](https://github.com/kevboh/longform/blob/main/src/main.ts#L268) key, which I'm not sure if that is meant to be in the production build? Seems like dev logging to me but I've only skimmed the codebase. But since it changes frequently, it makes pulling the latest from git awkward.

**Comment by kevboh** [comment]
Test entry removed in 5fce39c0972248ee6eac86c9835421afcde8e7c9, looking at the larger feature next.

**Comment by kevboh** [comment]
This will be available in the next beta. Added the option to store to a hardcoded path in the plugin folder or an arbitrary json file in your vault.

**Comment by kevboh** [comment]
Just re-upped the beta. Hopefully the last one before a general release. You'll have to remove and reinstall via BRAT to test.

**Comment by chrisgrieser** [comment]
can confirm that it works.

For anyone finding this issue via search: After enabling the separation of session and config data in the settings, you can add this to your gitignore:
```gitignore
.obsidian/plugins/longform/sessions.json
```
